baseurl                 = "/"
relativeURLs            = true
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "MPI CBS Christmas Party 2020 - Open Science Escape Room"
theme                   = "sam"
pygmentsStyle           = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
publishDir              = "docs"
googleAnalytics         = "G-0CS8JKDMHZ"

[markup.goldmark.renderer]
      unsafe = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "images/norment.png"
    homepage            = "home"                           # What to call the home page link
    footerText          = ""
    companylogo         = "images/cbs-osi-logo-crop.jpg"
    logoheight          = "100px"
    companysite         = "https://www.cbs.mpg.de/en/cbs-open-science"

# Metadata for Open Graph and Twitter
    description         = "Interactive site for the Escape Room at the MPI CBS Christmas Party 2020"
    images              = ["images/cbs-osi-logo-crop.jpg"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title               = "Open Science Escape Room"
    # rss               = ""

[[params.videoBackground.sources]]
    source  = "images/Christmas_EscapeRoom.mp4"
    type    = "video/mp4"
    poster  = "images/background.jpg"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.6)" # optional

#[[params.mainMenu]]
#    link = "pages/program"
#    text = "program"
#[[params.mainMenu]]
#    link = "/items/closed"
#    text = "THE ESCAPE ROOM IS CLOSED"
[[params.mainMenu]]
    link = "introduction"
    text = "start"
[[params.mainMenu]]
    link = "tasks"
    text = "tasks"
[[params.mainMenu]]
    link = "instructions"
    text = "instructions"
[[params.mainMenu]]
    link = "about"
    text = "about"

[imaging]
    quality = 75
